/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchivedRouteImport } from './routes/archived'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as QuestionsIndexRouteImport } from './routes/questions/index'
import { Route as QuestionsIdRouteImport } from './routes/questions/$id'
import { Route as QuestionsCreateRouteImport } from './routes/questions/create'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as QuestionsIdIndexRouteImport } from './routes/questions/$id.index'
import { Route as QuestionsIdEditRouteImport } from './routes/questions/$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivedRoute = ArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsIndexRoute = QuestionsIndexRouteImport.update({
  id: '/questions/',
  path: '/questions/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsIdRoute = QuestionsIdRouteImport.update({
  id: '/questions/$id',
  path: '/questions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsCreateRoute = QuestionsCreateRouteImport.update({
  id: '/questions/create',
  path: '/questions/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsIdIndexRoute = QuestionsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QuestionsIdRoute,
} as any)
const QuestionsIdEditRoute = QuestionsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => QuestionsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archived': typeof ArchivedRoute
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/questions/$id': typeof QuestionsIdRouteWithChildren
  '/questions/create': typeof QuestionsCreateRoute
  '/questions/': typeof QuestionsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/questions/$id/edit': typeof QuestionsIdEditRoute
  '/questions/$id/': typeof QuestionsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archived': typeof ArchivedRoute
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/questions/create': typeof QuestionsCreateRoute
  '/questions': typeof QuestionsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/questions/$id/edit': typeof QuestionsIdEditRoute
  '/questions/$id': typeof QuestionsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archived': typeof ArchivedRoute
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/questions/$id': typeof QuestionsIdRouteWithChildren
  '/questions/create': typeof QuestionsCreateRoute
  '/questions/': typeof QuestionsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/questions/$id/edit': typeof QuestionsIdEditRoute
  '/questions/$id/': typeof QuestionsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archived'
    | '/login'
    | '/sign-up'
    | '/questions/$id'
    | '/questions/create'
    | '/questions/'
    | '/api/auth/$'
    | '/questions/$id/edit'
    | '/questions/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archived'
    | '/login'
    | '/sign-up'
    | '/questions/create'
    | '/questions'
    | '/api/auth/$'
    | '/questions/$id/edit'
    | '/questions/$id'
  id:
    | '__root__'
    | '/'
    | '/archived'
    | '/login'
    | '/sign-up'
    | '/questions/$id'
    | '/questions/create'
    | '/questions/'
    | '/api/auth/$'
    | '/questions/$id/edit'
    | '/questions/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchivedRoute: typeof ArchivedRoute
  LoginRoute: typeof LoginRoute
  SignUpRoute: typeof SignUpRoute
  QuestionsIdRoute: typeof QuestionsIdRouteWithChildren
  QuestionsCreateRoute: typeof QuestionsCreateRoute
  QuestionsIndexRoute: typeof QuestionsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archived': {
      id: '/archived'
      path: '/archived'
      fullPath: '/archived'
      preLoaderRoute: typeof ArchivedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/': {
      id: '/questions/'
      path: '/questions'
      fullPath: '/questions/'
      preLoaderRoute: typeof QuestionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/$id': {
      id: '/questions/$id'
      path: '/questions/$id'
      fullPath: '/questions/$id'
      preLoaderRoute: typeof QuestionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/create': {
      id: '/questions/create'
      path: '/questions/create'
      fullPath: '/questions/create'
      preLoaderRoute: typeof QuestionsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/$id/': {
      id: '/questions/$id/'
      path: '/'
      fullPath: '/questions/$id/'
      preLoaderRoute: typeof QuestionsIdIndexRouteImport
      parentRoute: typeof QuestionsIdRoute
    }
    '/questions/$id/edit': {
      id: '/questions/$id/edit'
      path: '/edit'
      fullPath: '/questions/$id/edit'
      preLoaderRoute: typeof QuestionsIdEditRouteImport
      parentRoute: typeof QuestionsIdRoute
    }
  }
}

interface QuestionsIdRouteChildren {
  QuestionsIdEditRoute: typeof QuestionsIdEditRoute
  QuestionsIdIndexRoute: typeof QuestionsIdIndexRoute
}

const QuestionsIdRouteChildren: QuestionsIdRouteChildren = {
  QuestionsIdEditRoute: QuestionsIdEditRoute,
  QuestionsIdIndexRoute: QuestionsIdIndexRoute,
}

const QuestionsIdRouteWithChildren = QuestionsIdRoute._addFileChildren(
  QuestionsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchivedRoute: ArchivedRoute,
  LoginRoute: LoginRoute,
  SignUpRoute: SignUpRoute,
  QuestionsIdRoute: QuestionsIdRouteWithChildren,
  QuestionsCreateRoute: QuestionsCreateRoute,
  QuestionsIndexRoute: QuestionsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
